name: bayesian_nn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.0
  - ignite
  - ipython
  - jupyter
  - matplotlib
  - notebook
  - nltk
  - numpy
  - pip
  - python=3.6
  - pytorch
  - spacy
  - torchvision
  - pip:
    - torchtext
